steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/evident-galaxy-193006/catears:latest', '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/evident-galaxy-193006/catears']
images: ['gcr.io/evident-galaxy-193006/catears:latest']
