steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/evident-galaxy-193006/catears:latest', '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/evident-galaxy-193006/catears']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'catears', '--image', 'gcr.io/evident-galaxy-193006/catears', '--region', 'us-central1' ]
images: ['gcr.io/evident-galaxy-193006/catears:latest']
